var annotated_dup =
[
    [ "Hermes", "namespace_hermes.html", [
      [ "_details", "namespace_hermes_1_1__details.html", [
        [ "AcceptOptionsIpv6Base", "struct_hermes_1_1__details_1_1_accept_options_ipv6_base.html", null ],
        [ "AcceptOptionsIpv6Base< AddressFamilyEnum::Inet6 >", "struct_hermes_1_1__details_1_1_accept_options_ipv6_base_3_01_address_family_enum_1_1_inet6_01_4.html", "struct_hermes_1_1__details_1_1_accept_options_ipv6_base_3_01_address_family_enum_1_1_inet6_01_4" ],
        [ "ConnectOptionsIpv6Base", "struct_hermes_1_1__details_1_1_connect_options_ipv6_base.html", null ],
        [ "ConnectOptionsIpv6Base< AddressFamilyEnum::Inet6 >", "struct_hermes_1_1__details_1_1_connect_options_ipv6_base_3_01_address_family_enum_1_1_inet6_01_4.html", "struct_hermes_1_1__details_1_1_connect_options_ipv6_base_3_01_address_family_enum_1_1_inet6_01_4" ],
        [ "ITlsAcceptStateMachine", "struct_hermes_1_1__details_1_1_i_tls_accept_state_machine.html", "struct_hermes_1_1__details_1_1_i_tls_accept_state_machine" ],
        [ "ITlsConnectStateMachine", "struct_hermes_1_1__details_1_1_i_tls_connect_state_machine.html", "struct_hermes_1_1__details_1_1_i_tls_connect_state_machine" ],
        [ "ITlsTransferStateMachine", "struct_hermes_1_1__details_1_1_i_tls_transfer_state_machine.html", "struct_hermes_1_1__details_1_1_i_tls_transfer_state_machine" ],
        [ "OptionsTcpNoDelayBase", "struct_hermes_1_1__details_1_1_options_tcp_no_delay_base.html", null ],
        [ "OptionsTcpNoDelayBase< SocketTypeEnum::Stream >", "struct_hermes_1_1__details_1_1_options_tcp_no_delay_base_3_01_socket_type_enum_1_1_stream_01_4.html", "struct_hermes_1_1__details_1_1_options_tcp_no_delay_base_3_01_socket_type_enum_1_1_stream_01_4" ],
        [ "TlsAcceptStateMachine", "struct_hermes_1_1__details_1_1_tls_accept_state_machine.html", "struct_hermes_1_1__details_1_1_tls_accept_state_machine" ],
        [ "TlsConnectStateMachine", "struct_hermes_1_1__details_1_1_tls_connect_state_machine.html", "struct_hermes_1_1__details_1_1_tls_connect_state_machine" ],
        [ "TlsSession", "struct_hermes_1_1__details_1_1_tls_session.html", "struct_hermes_1_1__details_1_1_tls_session" ],
        [ "TlsTransferStateMachine", "struct_hermes_1_1__details_1_1_tls_transfer_state_machine.html", "struct_hermes_1_1__details_1_1_tls_transfer_state_machine" ]
      ] ],
      [ "Utils", "namespace_hermes_1_1_utils.html", [
        [ "DropLastAdaptor", "struct_hermes_1_1_utils_1_1_drop_last_adaptor.html", "struct_hermes_1_1_utils_1_1_drop_last_adaptor" ],
        [ "DropLastView", "struct_hermes_1_1_utils_1_1_drop_last_view.html", "struct_hermes_1_1_utils_1_1_drop_last_view" ],
        [ "Overloaded", "struct_hermes_1_1_utils_1_1_overloaded.html", null ],
        [ "UntilMatchAdaptor", "struct_hermes_1_1_utils_1_1_until_match_adaptor.html", "struct_hermes_1_1_utils_1_1_until_match_adaptor" ],
        [ "UntilMatchView", "struct_hermes_1_1_utils_1_1_until_match_view.html", "struct_hermes_1_1_utils_1_1_until_match_view" ]
      ] ],
      [ "AsyncClientSocket", "struct_hermes_1_1_async_client_socket.html", "struct_hermes_1_1_async_client_socket" ],
      [ "AsyncListenerSocket", "struct_hermes_1_1_async_listener_socket.html", "struct_hermes_1_1_async_listener_socket" ],
      [ "AsyncServerSocket", "struct_hermes_1_1_async_server_socket.html", "struct_hermes_1_1_async_server_socket" ],
      [ "ClientSocket", "struct_hermes_1_1_client_socket.html", "struct_hermes_1_1_client_socket" ],
      [ "Credentials", "struct_hermes_1_1_credentials.html", "struct_hermes_1_1_credentials" ],
      [ "DefaultAcceptPolicy", "struct_hermes_1_1_default_accept_policy.html", "struct_hermes_1_1_default_accept_policy" ],
      [ "DefaultAsyncAcceptPolicy", "struct_hermes_1_1_default_async_accept_policy.html", "struct_hermes_1_1_default_async_accept_policy" ],
      [ "DefaultAsyncConnectPolicy", "struct_hermes_1_1_default_async_connect_policy.html", "struct_hermes_1_1_default_async_connect_policy" ],
      [ "DefaultAsyncTransferPolicy", "struct_hermes_1_1_default_async_transfer_policy.html", "struct_hermes_1_1_default_async_transfer_policy" ],
      [ "DefaultConnectPolicy", "struct_hermes_1_1_default_connect_policy.html", "struct_hermes_1_1_default_connect_policy" ],
      [ "DefaultSocketData", "struct_hermes_1_1_default_socket_data.html", "struct_hermes_1_1_default_socket_data" ],
      [ "DefaultTransferPolicy", "struct_hermes_1_1_default_transfer_policy.html", "struct_hermes_1_1_default_transfer_policy" ],
      [ "FastIoLoop", "class_hermes_1_1_fast_io_loop.html", "class_hermes_1_1_fast_io_loop" ],
      [ "FastIoScheduler", "struct_hermes_1_1_fast_io_scheduler.html", "struct_hermes_1_1_fast_io_scheduler" ],
      [ "FastIoScheduleSender", "struct_hermes_1_1_fast_io_schedule_sender.html", "struct_hermes_1_1_fast_io_schedule_sender" ],
      [ "IpAddress", "struct_hermes_1_1_ip_address.html", "struct_hermes_1_1_ip_address" ],
      [ "IpEndpoint", "struct_hermes_1_1_ip_endpoint.html", "struct_hermes_1_1_ip_endpoint" ],
      [ "IpEndpointParams", "struct_hermes_1_1_ip_endpoint_params.html", "struct_hermes_1_1_ip_endpoint_params" ],
      [ "ListenerSocket", "struct_hermes_1_1_listener_socket.html", "struct_hermes_1_1_listener_socket" ],
      [ "Network", "struct_hermes_1_1_network.html", "struct_hermes_1_1_network" ],
      [ "ServerSocket", "struct_hermes_1_1_server_socket.html", "struct_hermes_1_1_server_socket" ],
      [ "TlsAcceptPolicy", "struct_hermes_1_1_tls_accept_policy.html", "struct_hermes_1_1_tls_accept_policy" ],
      [ "TlsAsyncAcceptPolicy", "struct_hermes_1_1_tls_async_accept_policy.html", "struct_hermes_1_1_tls_async_accept_policy" ],
      [ "TlsAsyncConnectPolicy", "struct_hermes_1_1_tls_async_connect_policy.html", "struct_hermes_1_1_tls_async_connect_policy" ],
      [ "TlsAsyncTransferPolicy", "struct_hermes_1_1_tls_async_transfer_policy.html", "struct_hermes_1_1_tls_async_transfer_policy" ],
      [ "TlsConnectPolicy", "struct_hermes_1_1_tls_connect_policy.html", "struct_hermes_1_1_tls_connect_policy" ],
      [ "TlsSocketData", "struct_hermes_1_1_tls_socket_data.html", "struct_hermes_1_1_tls_socket_data" ],
      [ "TlsTransferPolicy", "struct_hermes_1_1_tls_transfer_policy.html", "struct_hermes_1_1_tls_transfer_policy" ],
      [ "TransferError", "struct_hermes_1_1_transfer_error.html", "struct_hermes_1_1_transfer_error" ],
      [ "TransferOperStatus", "struct_hermes_1_1_transfer_oper_status.html", "struct_hermes_1_1_transfer_oper_status" ]
    ] ]
];