var searchData=
[
  ['c_20ranges_20compatible_0',['Using &lt;span class=&quot;tt&quot;&gt;RecvRange&lt;/span&gt; (C++ Ranges Compatible)',['../recv-stream-behavior.html#autotoc_md24',1,'']]],
  ['calling_20send_20and_20lifting_20directly_1',['Why a factory instead of calling Send and lifting directly',['../send-lift-pattern.html#autotoc_md64',1,'']]],
  ['centering_2',['Centering',['../md_docs_2doxygen_2docs_2theme-reference_2tricks.html#autotoc_md45',1,'']]],
  ['choosing_20sidebar_20width_3',['Choosing Sidebar Width',['../md_docs_2doxygen_2docs_2theme-reference_2tricks.html#tricks-sidebar',1,'']]],
  ['cleanup_4',['Cleanup',['../concept_hermes_1_1_connection_policy_concept.html#autotoc_md70',1,'Cleanup'],['../concept_hermes_1_1_accept_policy_concept.html#autotoc_md83',1,'Cleanup']]],
  ['client_5',['Client',['../getting-started.html#autotoc_md75',1,'Client'],['../getting-started.html#autotoc_md78',1,'Client']]],
  ['cmake_6',['Manual (CMake)',['../index.html#autotoc_md7',1,'']]],
  ['comparative_20example_7',['Comparative Example',['../recv-stream-behavior.html#autotoc_md22',1,'']]],
  ['compatible_8',['Using &lt;span class=&quot;tt&quot;&gt;RecvRange&lt;/span&gt; (C++ Ranges Compatible)',['../recv-stream-behavior.html#autotoc_md24',1,'']]],
  ['composes_20the_20lego_9',['How the facade composes the lego',['../policy-architecture.html#autotoc_md32',1,'']]],
  ['composition_20and_20options_10',['Policy composition and options',['../policy-architecture.html#autotoc_md34',1,'']]],
  ['composition_20with_20and_5fthen_11',['Composition with and_then',['../send-lift-pattern.html',1,'SendAndLift and Composition with and_then'],['../send-lift-pattern.html#autotoc_md61',1,'SendAndLift and Composition with and_then']]],
  ['configuration_12',['Configuration',['../concept_hermes_1_1_connection_policy_concept.html#autotoc_md68',1,'Configuration'],['../concept_hermes_1_1_accept_policy_concept.html#autotoc_md80',1,'Configuration']]],
  ['connection_13',['Connection',['../concept_hermes_1_1_connection_policy_concept.html#autotoc_md69',1,'Connection'],['../concept_hermes_1_1_accept_policy_concept.html#autotoc_md82',1,'Connection']]],
  ['connection_14',['connection',['../policy-architecture.html#autotoc_md30',1,'Accept policy: creating an incoming connection'],['../policy-architecture.html#autotoc_md29',1,'Connection policy: creating an outgoing connection']]],
  ['connection_20options_15',['Connection options',['../policy-options.html#autotoc_md40',1,'']]],
  ['connection_20policy_3a_20creating_20an_20outgoing_20connection_16',['Connection policy: creating an outgoing connection',['../policy-architecture.html#autotoc_md29',1,'']]],
  ['copy_20button_17',['Fragment Copy Button',['../md_docs_2doxygen_2docs_2theme-reference_2extensions.html#extension-copy-button',1,'']]],
  ['core_20mechanics_3a_20operator_20vs_20operator_18',['Core Mechanics: &lt;span class=&quot;tt&quot;&gt;operator*&lt;/span&gt; vs &lt;span class=&quot;tt&quot;&gt;operator++&lt;/span&gt;',['../recv-stream-behavior.html#autotoc_md17',1,'']]],
  ['creating_20an_20incoming_20connection_19',['Accept policy: creating an incoming connection',['../policy-architecture.html#autotoc_md30',1,'']]],
  ['creating_20an_20outgoing_20connection_20',['Connection policy: creating an outgoing connection',['../policy-architecture.html#autotoc_md29',1,'']]],
  ['css_20variables_21',['CSS-Variables',['../md_docs_2doxygen_2docs_2theme-reference_2customization.html#autotoc_md87',1,'']]],
  ['custom_20policy_22',['Designing a custom policy',['../policy-architecture.html#autotoc_md33',1,'']]],
  ['customization_23',['Customization',['../md_docs_2doxygen_2docs_2theme-reference_2customization.html',1,'']]],
  ['customizations_24',['Share your customizations',['../md_docs_2doxygen_2docs_2theme-reference_2customization.html#autotoc_md91',1,'']]],
  ['customizing_25',['Customizing',['../md_docs_2doxygen_2docs_2theme-reference_2extensions.html#autotoc_md48',1,'Customizing'],['../md_docs_2doxygen_2docs_2theme-reference_2extensions.html#autotoc_md52',1,'Customizing'],['../md_docs_2doxygen_2docs_2theme-reference_2extensions.html#autotoc_md54',1,'Customizing'],['../md_docs_2doxygen_2docs_2theme-reference_2extensions.html#autotoc_md56',1,'Customizing']]]
];
