#pragma once
#include <sspi.h>

enum class InitializeSecurityContextReturnFlags : long long {
    RET_DELEGATE               = ISC_RET_DELEGATE,
    RET_MUTUAL_AUTH            = ISC_RET_MUTUAL_AUTH,
    RET_REPLAY_DETECT          = ISC_RET_REPLAY_DETECT,
    RET_SEQUENCE_DETECT        = ISC_RET_SEQUENCE_DETECT,
    RET_CONFIDENTIALITY        = ISC_RET_CONFIDENTIALITY,
    RET_USE_SESSION_KEY        = ISC_RET_USE_SESSION_KEY,
    RET_USED_COLLECTED_CREDS   = ISC_RET_USED_COLLECTED_CREDS,
    RET_USED_SUPPLIED_CREDS    = ISC_RET_USED_SUPPLIED_CREDS,
    RET_ALLOCATED_MEMORY       = ISC_RET_ALLOCATED_MEMORY,
    RET_USED_DCE_STYLE         = ISC_RET_USED_DCE_STYLE,
    RET_DATAGRAM               = ISC_RET_DATAGRAM,
    RET_CONNECTION             = ISC_RET_CONNECTION,
    RET_INTERMEDIATE_RETURN    = ISC_RET_INTERMEDIATE_RETURN,
    RET_CALL_LEVEL             = ISC_RET_CALL_LEVEL,
    RET_EXTENDED_ERROR         = ISC_RET_EXTENDED_ERROR,
    RET_STREAM                 = ISC_RET_STREAM,
    RET_INTEGRITY              = ISC_RET_INTEGRITY,
    RET_IDENTIFY               = ISC_RET_IDENTIFY,
    RET_NULL_SESSION           = ISC_RET_NULL_SESSION,
    RET_MANUAL_CRED_VALIDATION = ISC_RET_MANUAL_CRED_VALIDATION,
    RET_RESERVED1              = ISC_RET_RESERVED1,
    RET_FRAGMENT_ONLY          = ISC_RET_FRAGMENT_ONLY,
    // This exists only in Windows Vista and greater
    RET_FORWARD_CREDENTIALS = ISC_RET_FORWARD_CREDENTIALS,

    RET_USED_HTTP_STYLE          = ISC_RET_USED_HTTP_STYLE,
    RET_NO_ADDITIONAL_TOKEN      = ISC_RET_NO_ADDITIONAL_TOKEN,
    RET_REAUTHENTICATION         = ISC_RET_REAUTHENTICATION,
    RET_CONFIDENTIALITY_ONLY     = ISC_RET_CONFIDENTIALITY_ONLY,
    RET_MESSAGES                 = ISC_RET_MESSAGES,
    RET_DEFERRED_CRED_VALIDATION = ISC_RET_DEFERRED_CRED_VALIDATION,
    RET_NO_POST_HANDSHAKE_AUTH   = ISC_RET_NO_POST_HANDSHAKE_AUTH,
};
