#pragma once
#include <schannel.h>

enum class SupportedProtocolsFlags : long long {
    PCT1_SERVER = SP_PROT_PCT1_SERVER,
    PCT1_CLIENT = SP_PROT_PCT1_CLIENT,
    PCT1        = SP_PROT_PCT1,

    SSL2_SERVER = SP_PROT_SSL2_SERVER,
    SSL2_CLIENT = SP_PROT_SSL2_CLIENT,
    SSL2        = SP_PROT_SSL2,

    SSL3_SERVER = SP_PROT_SSL3_SERVER,
    SSL3_CLIENT = SP_PROT_SSL3_CLIENT,
    SSL3        = SP_PROT_SSL3,

    TLS1_SERVER = SP_PROT_TLS1_SERVER,
    TLS1_CLIENT = SP_PROT_TLS1_CLIENT,
    TLS1        = SP_PROT_TLS1,

    SSL3TLS1_CLIENTS = SP_PROT_SSL3TLS1_CLIENTS,
    SSL3TLS1_SERVERS = SP_PROT_SSL3TLS1_SERVERS,
    SSL3TLS1         = SP_PROT_SSL3TLS1,

    UNI_SERVER = SP_PROT_UNI_SERVER,
    UNI_CLIENT = SP_PROT_UNI_CLIENT,
    UNI        = SP_PROT_UNI,

    ALL     = SP_PROT_ALL,
    NONE    = SP_PROT_NONE,
    CLIENTS = SP_PROT_CLIENTS,
    SERVERS = SP_PROT_SERVERS,


    TLS1_0_SERVER = SP_PROT_TLS1_0_SERVER,
    TLS1_0_CLIENT = SP_PROT_TLS1_0_CLIENT,
    TLS1_0        = SP_PROT_TLS1_0,

    TLS1_1_SERVER = SP_PROT_TLS1_1_SERVER,
    TLS1_1_CLIENT = SP_PROT_TLS1_1_CLIENT,
    TLS1_1        = SP_PROT_TLS1_1,

    TLS1_2_SERVER = SP_PROT_TLS1_2_SERVER,
    TLS1_2_CLIENT = SP_PROT_TLS1_2_CLIENT,
    TLS1_2        = SP_PROT_TLS1_2,

    TLS1_3_SERVER = SP_PROT_TLS1_3_SERVER,
    TLS1_3_CLIENT = SP_PROT_TLS1_3_CLIENT,
    TLS1_3        = SP_PROT_TLS1_3,

    DTLS_SERVER = SP_PROT_DTLS_SERVER,
    DTLS_CLIENT = SP_PROT_DTLS_CLIENT,
    DTLS        = SP_PROT_DTLS,

    DTLS1_0_SERVER = SP_PROT_DTLS1_0_SERVER,
    DTLS1_0_CLIENT = SP_PROT_DTLS1_0_CLIENT,
    DTLS1_0        = SP_PROT_DTLS1_0,

    DTLS1_2_SERVER = SP_PROT_DTLS1_2_SERVER,
    DTLS1_2_CLIENT = SP_PROT_DTLS1_2_CLIENT,
    DTLS1_2        = SP_PROT_DTLS1_2,

    DTLS1_X_SERVER = SP_PROT_DTLS1_X_SERVER,

    DTLS1_X_CLIENT = SP_PROT_DTLS1_X_CLIENT,

    DTLS1_X = SP_PROT_DTLS1_X,

    TLS1_1PLUS_SERVER = SP_PROT_TLS1_1PLUS_SERVER,
    TLS1_1PLUS_CLIENT = SP_PROT_TLS1_1PLUS_CLIENT,

    TLS1_1PLUS = SP_PROT_TLS1_1PLUS,

    TLS1_3PLUS_SERVER = SP_PROT_TLS1_3PLUS_SERVER,
    TLS1_3PLUS_CLIENT = SP_PROT_TLS1_3PLUS_CLIENT,
    TLS1_3PLUS        = SP_PROT_TLS1_3PLUS,

    TLS1_X_SERVER = SP_PROT_TLS1_X_SERVER,
    TLS1_X_CLIENT = SP_PROT_TLS1_X_CLIENT,
    TLS1_X        = SP_PROT_TLS1_X,

    SSL3TLS1_X_CLIENTS = SP_PROT_SSL3TLS1_X_CLIENTS,
    SSL3TLS1_X_SERVERS = SP_PROT_SSL3TLS1_X_SERVERS,
    SSL3TLS1_X         = SP_PROT_SSL3TLS1_X,

    X_CLIENTS = SP_PROT_X_CLIENTS,
    X_SERVERS = SP_PROT_X_SERVERS
};
